server:
  port: ${SERVER_PORT}
  error:
    include-stacktrace: never
    include-binding-errors: never
    include-message: always

  forward-headers-strategy: framework

spring:
  application:
    name: vm

  datasource:
    driver-class-name: ${DATABASE_NAME}
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        jdbc:
          time_zone: Asia/Seoul
        dialect: ${DATABASE_DIALECT}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_ISSUER_URI}