server:
  port: ${SERVER_PORT}
  error:
    include-stacktrace: never
    include-binding-errors: never
    include-message: always

  forward-headers-strategy: framework

spring:
  application:
    name: vm

  mvc:
    async:
      request-timeout: 180s

  r2dbc:
    url: ${DATABASE_REACTIVE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    pool:
      enabled: true
      initial-size: 10
      max-size: 50
      max-idle-time: 30s

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KC_ISSUER_URI}

custom:
  audience: ${SERVICE_AUD}
  kc:
    token-endpoint: ${KC_TOKEN_ENDPOINT}
    client-id: ${KC_CLIENT_ID}
    client-secret: ${KC_CLIENT_SECRET}
  user:
    audience: ${USER_SERVICE_AUD}
    base-url: ${USER_SERVICE_BASE_URL}
  proxmox:
    base-url: ${PROXMOX_BASE_URL}
    token-id: ${PROXMOX_TOKEN_ID}
    token-value: ${PROXMOX_TOKEN_VALUE}
    template:
      free: ${PROXMOX_FREE}
      pro: ${PROXMOX_PRO}

logging:
  level:
    org.springframework.data.r2dbc: DEBUG
    org.springframework.data.relational.core.mapping: DEBUG